name: Github Pages Deploy
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and build
        working-directory: ./meow-meal-manager
        run: npm install && npm run build && cp dist/meow-meal-manager/browser/index.html dist/meow-meal-manager/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v6
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: meow-meal-manager/dist/meow-meal-manager/browser # The folder the action should deploy.
